### PR TITLE
Rename LICENSE to Round No:180753306711255552JX0N4 Seed:KCjN64iiZBHZb…

### PR DESCRIPTION
**Pull request by Jithinvr00**
…5U1gvxgyg4fVae0EATOa5p0tZUR Seed Cipher:5f41d72f6ab9a60e5c0704ee441ce6d39aefe2e6f28377a89fe0cb2ed886eb13 Result:3.23 Seed and result:KCjN64iiZBHZb5U1gvxgyg4fVae0EATOa5p0tZUR3.23 Result Cipher:71b009b5669543958261016ac024decffd890ec643e6f99f2cb8981edab88183

### CODE REVIEW

**Review by Abubakarumair — APPROVED** [review]

**Comment by Aviator68930** [comment]
Please send code

**Comment by Aviator68930** [comment]
Please send me code

**Comment by Rahi011** [comment]
Send me aviator predicator app code

**Comment by TRUKFIT021** [comment]
Send me the avatar code

**Comment by saieam** [comment]
Please sent me the code please

**Pull request closed without merging**
